site_name: Turtle AI
site_description: A minimal AI toolkit
site_url: https://xuehangai.github.io/turtle-ai/
repo_url: https://github.com/XUEHANGAI/turtle-ai
repo_name: XUEHANGAI/turtle-ai

theme:
  name: material
  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to system preference
  features:
    - navigation.instant
    - search.highlight
    - content.code.copy

nav:
  - Home: index.md

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.superfences
