[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "turtle-ai"
version = "0.1.1"
description = "Turtle AI"
readme = "README.md"
license = {text = "MIT"}
requires-python = ">=3.13"
dependencies = []

[project.scripts]
turtle-ai = "test:main"

[project.urls]
Homepage = "http://xuehang.ai"
Repository = "https://github.com/XUEHANGAI/turtle-ai"

[tool.hatch.build.targets.wheel]
packages = ["turtleai", "test.py"]
